### PR TITLE
Add exuberant-ctags to required packages to build and Debian as supported OS

### PR DESCRIPTION
**Pull request by 17Genr**
-- added Debian as a supported OS alongside Ubuntu

-- added 'exuberant-ctags' to apt-get package list

-- added 'exuberant-ctags' to yum package list (untested, assuming
   same package name as apt)

ps. I'm still new to using github.  I'll get the commit message right next time :)

### CODE REVIEW

**Comment by johncburnham** [comment]
the yum package is just called ctags. Ref: http://blog.johngoulah.com/tag/ack/

**Comment by johncburnham** [comment]
And why exactly do we need ctags?

**Comment by 17Genr** [comment]
I tried running 'make tags' on my Debian Testing machine and the one that I had installed (maybe by vim) didn't support the --exclude option.  Calling either 'apt-get install ctags' or 'apt-get install exuberant-ctags' installs a ctags that supports that option.

**Comment by 17Genr** [comment]
After doing that I found out that the tags format for ctags isn't supported by emacs without extra options.  I've got another commit to add 'make etags' that uses etags that comes with an emacs install.

**Pull request merged**
